Add missing includes for byte swap operations
Fixes bunch of following issues:

 CMakeFiles/mktplinkfw2.dir/src/mktplinkfw2.c.o: In function `fill_header':
 mktplinkfw2.c:(.text+0xad): undefined reference to `bswap_32'

Signed-off-by: Petr Štetiar <ynezz@true.cz>